# version: '3'

# services:
#   db:
#     image: postgres:14.3
#     restart: always
#     ports:
#       - '5432:5432'
#     environment:
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     container_name: teslodb
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
# no funciona la de la clase por permisos
version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslo
    volumes:
      - psql:/var/lib/postgresql/data
volumes:
  psql:
# version: '3' funcionas

# services:
#   db:
#     image: postgres:14.3
#     restart: on-failure
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#       PGDATA: /var/lib/postgresql/data/pgdata
#     container_name: teslo
#     volumes:
#       - ./postgres_data:/var/lib/postgresql
